blank_issues_enabled: true
contact_links:
  - name: Accelerate discussions
    about: Ask and answer questions here
    url: https://github.com/AccelerateHS/accelerate/discussions
  - name: Accelerate community chat
    about: Ask and answer questions here
    url: https://gitter.im/AccelerateHS/Lobby
  - name: Accelerate mailing list
    about: Ask and answer questions here
    url: http://groups.google.com/group/accelerate-haskell
    # url: mailto:accelerate-haskell@googlegroups.com

